import { BaseMessageHandler, ProcessedMessage } from './MessageHandler';
import { BlueBubblesMessage } from '../types';
import { logDebug } from '../utils/logger';

/**
 * Handler for reaction-only events generated by BlueBubbles.
 * These events are metadata only, so we currently skip them.
 * Also handles tapback reaction text messages (e.g., "Liked 'message'", "Loved 'message'").
 */
export class ReactionHandler extends BaseMessageHandler {
  // Regex to match tapback reaction text patterns
  private static readonly TAPBACK_TEXT_PATTERNS = [
    /^Liked "/i,
    /^Loved "/i,
    /^Disliked "/i,
    /^Laughed at "/i,
    /^Emphasized "/i,
    /^Questioned "/i,
    // Also match removal patterns
    /^Removed a like from "/i,
    /^Removed a heart from "/i,
    /^Removed a dislike from "/i,
    /^Removed a laugh from "/i,
    /^Removed an emphasis from "/i,
    /^Removed a question from "/i,
  ];

  getPriority(): number {
    // Highest priority so reactions are filtered early.
    return 15;
  }

  canHandle(message: BlueBubblesMessage): boolean {
    // BlueBubbles reactions typically arrive without text but with metadata we can detect
    // via attachments array or special guid suffix.
    const guid = message.guid || '';
    if (guid.includes('react-') || guid.includes('tapback-')) {
      return true;
    }

    // Also check for tapback text patterns (e.g., "Liked 'message'", "Loved 'message'")
    // These are generated when reactions are sent/received
    const text = message.text || '';
    if (text && ReactionHandler.TAPBACK_TEXT_PATTERNS.some(pattern => pattern.test(text))) {
      logDebug('Detected tapback text pattern', { textPreview: text.substring(0, 50) });
      return true;
    }

    return false;
  }

  async process(_message: BlueBubblesMessage): Promise<ProcessedMessage | null> {
    logDebug('Skipping reaction event');
    return null;
  }
}
