import { BaseMessageHandler, ProcessedMessage } from './MessageHandler';
import { BlueBubblesMessage } from '../types';
import { logDebug } from '../utils/logger';

/**
 * Handler for reaction-only events generated by BlueBubbles.
 * These events are metadata only, so we currently skip them.
 */
export class ReactionHandler extends BaseMessageHandler {
  getPriority(): number {
    // Highest priority so reactions are filtered early.
    return 15;
  }

  canHandle(message: BlueBubblesMessage): boolean {
    // BlueBubbles reactions typically arrive without text but with metadata we can detect
    // via attachments array or special guid suffix.
    const guid = message.guid || '';
    return guid.includes('react-') || guid.includes('tapback-');
  }

  async process(_message: BlueBubblesMessage): Promise<ProcessedMessage | null> {
    logDebug('Skipping reaction event');
    return null;
  }
}
